baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Home and Garden Haven'
theme = 'newsroom'
author = 'Garden Enthusiast'
canonifyurls = true
ignoreLogs = ['warning-goldmark-raw-html']

[pagination]
disableAliases = false
pagerSize = 10
path = 'page'

[permalinks]
pages = ':contentbasename/'

[params]
logo = ""
faviconsDir = "images/icons/"
blogDir = "posts"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
